AmbuShiftBundle\Entity\CrewPosition:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 50
    oneToMany:
        shiftWorkers:
            targetEntity: AmbuShiftBundle\Entity\ShiftWorker
            mappedBy: crewPosition
    manyToOne:
        vehicle:
            targetEntity: AmbuShiftBundle\Entity\Vehicle
            inversedBy: crewPositions
            joinColumn:
                name: vehicleId
                referencedColumnName: id