AmbuShiftBundle\Entity\Service:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 50
    oneToMany:
        shifts:
            targetEntity: AmbuShiftBundle\Entity\Shift
            mappedBy: service
            orphanRemoval: true
            cascade: ["persist", "remove"]
        timeSlots:
            targetEntity: AmbuShiftBundle\Entity\TimeSlot
            mappedBy: service
            orphanRemoval: true
            cascade: ["persist", "remove"]
        vehicles:
            targetEntity: AmbuShiftBundle\Entity\Vehicle
            mappedBy: service
            orphanRemoval: true
            cascade: ["persist", "remove"]