AmbuShiftBundle\Entity\Service:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 50