AmbuShiftBundle\Entity\Service:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 50
    oneToMany:
        shifts:
            targetEntity: AmbuShiftBundle\Entity\Shift
            mappedBy: shift
            orphanRemoval: true
            cascade: ["persist", "remove"]