AmbuShiftBundle\Entity\Shift:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        from:
            type: datetime
        to:
            type: datetime