AmbuShiftBundle\Entity\Shift:
    type:  entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        from:
            type: datetime
            column: "`from`"
        to:
            type: datetime
            column: "`to`"
    oneToMany:
        shiftWorkers:
            targetEntity: AmbuShiftBundle\Entity\ShiftWorker
            mappedBy: shiftWorker
            orphanRemoval: true
            cascade: ["persist", "remove"]    
    manyToOne:
        vehicle:
            targetEntity: AmbuShiftBundle\Entity\Vehicle
            inversedBy: vehicles
            joinColumn:
                name: vehicleId
                referencedColumnName: id
        operatingMonth:
            targetEntity: AmbuShiftBundle\Entity\OperatingMonth
            inversedBy: operatingMonths
            joinColumn:
                name: operatingMonthId
                referencedColumnName: id