home:
    path:     /
    defaults: { _controller: controller.home:indexAction }

shifts:
    path: /shifts
    defaults: { _controller: controller.shift:indexAction }

monthshifts:
    path: /shifts/{year}/{month}
    defaults: { _controller: controller.shift:indexAction }

shiftEnrollment:
    path:     /shifts/{shiftId}/crewPositions/{crewPositionId}/enroll
    defaults: { _controller: controller.shiftEnrollment:enrollAction }
    methods:  [POST]
    options:
      expose: true