services:
#    ambu_shift.example:
#        class: AmbuShiftBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  ambushiftnamingstrategy:
      class: AmbuShiftBundle\Repository\Doctrine\AmbuShiftNamingStrategy
      arguments: ["%table_prefix%"]